#!/usr/bin/env sh

set -e

uci set firewall.cjdnsport5201=rule
uci set firewall.cjdnsport5201.enabled='1'
uci set firewall.cjdnsport5201.name='Allow-iperf-cjdns'
uci set firewall.cjdnsport5201.src='cjdns'
uci set firewall.cjdnsport5201.proto='tcp'
uci set firewall.cjdnsport5201.dest_port='5201'
uci set firewall.cjdnsport5201.target='ACCEPT'

uci commit firewall

exit 0
