#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=85

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/transitd-server
  procd_set_param respawn
  procd_set_param file /opt/transitd/transitd.conf
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
